version: '3.3'

services:

  sospese-backend:
    container_name: sospese-backend
    restart: always
    build: .
    image: sospese-backend:1.0.0
    ports:
      - '3000:3000'
    expose:
      - '3000'
    depends_on:
      - nginx
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      - TZ=Europe/Rome
    ports:
      - "27017:27017"
    volumes:
      - /data/sospese:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/var/www/html
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/certbot/etc:/etc/letsencrypt
      - ./conf/certbot/var:/var/lib/letsencrypt

  certbot:
    container_name: certbot
    image: certbot/certbot
    networks:
      - nginx_net
    volumes:
      - ./conf/certbot/conf:/etc/letsencrypt
      - ./conf/certbot/www:/var/www/certbot
      - ./html:/var/www/html
    restart: unless-stopped
    command: certonly --webroot --webroot-path=/var/www/html --email info@webeetle.com --agree-tos --no-eff-email --staging -d api.sospese.io 
    depends_on:
      - nginx

    