version: '3.3'

services:

  sospese-backend:
    container_name: sospese-backend
    restart: always
    build: .
    image: sospese-backend:1.0.0
    ports:
      - '3000:3000'
    expose:
      - '3000'
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      - TZ=Europe/Rome
    ports:
      - "27017:27017"
    volumes:
      - /data/sospese:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx
    links:
      - sospese-backend
    depends_on:
      - sospese-backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./conf/dhparam:/etc/nginx/dhparam
      - ./conf/certbot/conf:/etc/nginx/ssl
      - ./conf/certbot/data:/usr/share/nginx/html/letsencrypt

 certbot:
   container_name: certbot
   image: certbot/certbot
   links:
     - nginx
   volumes:
    - ./conf/certbot/conf:/etc/letsencrypt
    - ./conf/certbot/logs:/var/log/letsencrypt
    - ./conf/certbot/data:/usr/share/nginx/html/letsencrypt
   command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email info@webeetle.com --agree-tos --no-eff-email -d api.sospese.io 
   depends_on:
     - nginx
